import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, Plus, Minus, Sparkles, Clock } from 'lucide-react';
import { useHabitStore } from '@/stores/habitStore';
import type { HabitFrequency, HabitType } from '@/types/habit';
import { aiHabitSuggestionService } from '@/services/aiHabitSuggestionService';

interface AddHabitModalProps {
  open: boolean;
  onClose: () => void;
}

const EMOJI_OPTIONS = [
  '💧', '🏃', '📚', '✍️', '🧘', '💪', '🎨', '🎵', '🍎', '😴',
  '☕', '🌅', '🌙', '⭐', '🔥', '💡', '🎯', '📝', '🎮', '🏋️',
  '🚴', '🏊', '🧗', '⚽', '🎾', '🏀', '🎸', '🎹', '📷', '🎬',
];

export default function AddHabitModal({ open, onClose }: AddHabitModalProps) {
  const addHabit = useHabitStore((state) => state.addHabit);
  const habits = useHabitStore((state) => state.habits);
  
  const [name, setName] = useState('');
  const [emoji, setEmoji] = useState('⭐');
  const [frequency, setFrequency] = useState<HabitFrequency>('daily');
  const [type, setType] = useState<HabitType>('count');
  const [targetValue, setTargetValue] = useState(1);
  const [targetMode, setTargetMode] = useState<'frequency' | 'duration'>('frequency');
  const [description, setDescription] = useState('');
  const [keywords, setKeywords] = useState<string[]>([]);
  const [keywordInput, setKeywordInput] = useState('');
  const [enableRecognition, setEnableRecognition] = useState(false);
  const [isAILoading, setIsAILoading] = useState(false);
  
  // 反向检测规则
  const [enableReverseDetection, setEnableReverseDetection] = useState(false);
  const [reverseStartTime, setReverseStartTime] = useState('23:00');
  const [reverseEndTime, setReverseEndTime] = useState('05:00');
  const [reverseCrossDay, setReverseCrossDay] = useState(true);
  const [reverseKeywords, setReverseKeywords] = useState<string[]>([]);
  const [reverseKeywordInput, setReverseKeywordInput] = useState('');
  
  const handleAISuggest = async () => {
    if (!name.trim()) return;
    
    setIsAILoading(true);
    try {
      const suggestion = await aiHabitSuggestionService.suggestHabitConfig(name.trim());
      
      // 应用建议
      setEmoji(suggestion.emoji);
      setType(suggestion.type);
      setFrequency(suggestion.frequency);
      setTargetValue(suggestion.targetValue);
      setTargetMode(suggestion.targetMode);
      setDescription(suggestion.description);
      
      if (suggestion.keywords.length > 0) {
        setKeywords(suggestion.keywords);
        setEnableRecognition(true);
      }
      
      // 反向检测规则
      if (suggestion.reverseDetection?.enabled) {
        setEnableReverseDetection(true);
        setReverseStartTime(suggestion.reverseDetection.timeRange.startTime);
        setReverseEndTime(suggestion.reverseDetection.timeRange.endTime);
        setReverseCrossDay(suggestion.reverseDetection.timeRange.crossDay);
        setReverseKeywords(suggestion.reverseDetection.notFoundKeywords);
      }
    } catch (error) {
      console.error('AI 建议失败:', error);
      alert('AI 建议失败，请手动填写');
    } finally {
      setIsAILoading(false);
    }
  };
  
  const handleSubmit = () => {
    if (!name.trim()) return;
    
    addHabit({
      userId: 'local',
      name: name.trim(),
      emoji,
      description: description.trim() || undefined,
      type,
      frequency,
      targetValue,
      targetMode,
      targetPeriod: 1,
      recognitionRule: enableRecognition && (keywords.length > 0 || enableReverseDetection)
        ? {
            keywords,
            matchTitle: true,
            matchTags: true,
            reverseDetection: enableReverseDetection ? {
              enabled: true,
              timeRange: {
                startTime: reverseStartTime,
                endTime: reverseEndTime,
                crossDay: reverseCrossDay,
              },
              notFoundKeywords: reverseKeywords,
            } : undefined,
          }
        : undefined,
      autoGenerated: false,
      reminderEnabled: false,
      sortOrder: habits.length,
    });
    
    // 重置表单
    setName('');
    setEmoji('⭐');
    setFrequency('daily');
    setType('count');
    setTargetValue(1);
    setTargetMode('frequency');
    setDescription('');
    setKeywords([]);
    setKeywordInput('');
    setEnableRecognition(false);
    setEnableReverseDetection(false);
    setReverseKeywords([]);
    
    onClose();
  };
  
  const addKeyword = () => {
    const keyword = keywordInput.trim();
    if (keyword && !keywords.includes(keyword)) {
      setKeywords([...keywords, keyword]);
      setKeywordInput('');
    }
  };
  
  const removeKeyword = (keyword: string) => {
    setKeywords(keywords.filter((k) => k !== keyword));
  };
  
  const addReverseKeyword = () => {
    const keyword = reverseKeywordInput.trim();
    if (keyword && !reverseKeywords.includes(keyword)) {
      setReverseKeywords([...reverseKeywords, keyword]);
      setReverseKeywordInput('');
    }
  };
  
  const removeReverseKeyword = (keyword: string) => {
    setReverseKeywords(reverseKeywords.filter((k) => k !== keyword));
  };
  
  return (
    <AnimatePresence>
      {open && (
        <>
          {/* 背景遮罩 */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
            className="fixed inset-0 bg-black/50 backdrop-blur-sm"
            style={{ zIndex: 2147483648 }}
          />
          
          {/* 弹窗内容 */}
          <div
            className="fixed inset-0 flex items-end md:items-center justify-center p-0 md:p-4"
            style={{ zIndex: 2147483649 }}
          >
            <motion.div
              initial={{ y: '100%', opacity: 0 }}
              animate={{ y: 0, opacity: 1 }}
              exit={{ y: '100%', opacity: 0 }}
              transition={{ type: 'spring', damping: 30, stiffness: 300 }}
              className="rounded-t-3xl md:rounded-3xl w-full md:max-w-2xl h-[90vh] flex flex-col"
              style={{ backgroundColor: '#FFFFFF' }}
              onClick={(e) => e.stopPropagation()}
            >
              {/* 标题栏 */}
              <div className="border-b px-6 py-4 flex items-center justify-between flex-shrink-0" style={{
                backgroundColor: '#FFFFFF',
                borderColor: 'rgba(0, 0, 0, 0.06)'
              }}>
                <h2 className="text-xl font-bold" style={{ color: '#1D1D1F' }}>
                  新增习惯
                </h2>
                <button
                  onClick={onClose}
                  className="p-2 rounded-xl transition-colors active:scale-95"
                  style={{ backgroundColor: '#F5F5F7' }}
                >
                  <X className="w-5 h-5" style={{ color: 'rgba(60, 60, 67, 0.6)' }} />
                </button>
              </div>
              
              {/* 可滚动内容区域 */}
              <div className="p-6 space-y-6 overflow-y-auto flex-1">
                {/* Emoji 选择 */}
                <div>
                  <label className="block text-sm font-medium mb-3" style={{ color: '#1D1D1F' }}>
                    选择图标
                  </label>
                  <div className="grid grid-cols-10 gap-2">
                    {EMOJI_OPTIONS.map((e) => (
                      <button
                        key={e}
                        onClick={() => setEmoji(e)}
                        className="w-10 h-10 rounded-xl text-2xl flex items-center justify-center transition-all active:scale-95"
                        style={{
                          backgroundColor: emoji === e ? '#6D9978' : '#F5F5F7',
                          transform: emoji === e ? 'scale(1.1)' : 'scale(1)',
                          boxShadow: emoji === e ? '0 4px 12px rgba(109, 153, 120, 0.3)' : 'none'
                        }}
                      >
                        {e}
                      </button>
                    ))}
                  </div>
                </div>
                
                {/* 习惯名称 */}
                <div>
                  <label className="block text-sm font-medium mb-2" style={{ color: '#1D1D1F' }}>
                    习惯名称
                  </label>
                  <div className="flex gap-2">
                    <input
                      type="text"
                      value={name}
                      onChange={(e) => setName(e.target.value)}
                      placeholder="例如：每天喝水"
                      className="flex-1 px-4 py-3 rounded-xl border focus:outline-none"
                      style={{
                        backgroundColor: '#F5F5F7',
                        borderColor: 'rgba(0, 0, 0, 0.06)',
                        color: '#1D1D1F'
                      }}
                    />
                    <button
                      onClick={handleAISuggest}
                      disabled={!name.trim() || isAILoading}
                      className="px-4 py-3 rounded-full font-semibold text-sm shadow-lg transition-all active:scale-95 disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2 whitespace-nowrap"
                      style={{
                        backgroundColor: '#E8C259',
                        color: '#000000'
                      }}
                    >
                      {isAILoading ? (
                        <>
                          <motion.div
                            animate={{ rotate: 360 }}
                            transition={{ duration: 1, repeat: Infinity, ease: 'linear' }}
                          >
                            <Sparkles className="w-5 h-5" />
                          </motion.div>
                          <span>生成中</span>
                        </>
                      ) : (
                        <>
                          <Sparkles className="w-5 h-5" />
                          <span>智能填写</span>
                        </>
                      )}
                    </button>
                  </div>
                  <p className="text-xs mt-1" style={{ color: 'rgba(0, 0, 0, 0.5)' }}>
                    💡 输入习惯名称后，点击"智能填写"自动配置
                  </p>
                </div>
                
                {/* 类型选择 */}
                <div>
                  <label className="block text-sm font-medium mb-3" style={{ color: '#1D1D1F' }}>
                    类型
                  </label>
                  <div className="grid grid-cols-3 gap-3">
                    {[
                      { value: 'count' as const, label: '次数', emoji: '🔢' },
                      { value: 'duration' as const, label: '时长', emoji: '⏱️' },
                      { value: 'boolean' as const, label: '完成', emoji: '✅' },
                    ].map((t) => (
                      <button
                        key={t.value}
                        onClick={() => setType(t.value)}
                        className="p-4 rounded-xl border-2 transition-all active:scale-95"
                        style={{
                          borderColor: type === t.value ? '#6D9978' : 'rgba(0, 0, 0, 0.06)',
                          backgroundColor: type === t.value ? 'rgba(109, 153, 120, 0.1)' : '#FFFFFF'
                        }}
                      >
                        <div className="text-2xl mb-1">{t.emoji}</div>
                        <div className="text-sm font-medium" style={{ color: '#1D1D1F' }}>
                          {t.label}
                        </div>
                      </button>
                    ))}
                  </div>
                </div>
                
                {/* 目标模式选择 */}
                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-3">
                    目标模式
                  </label>
                  <div className="grid grid-cols-2 gap-3">
                    <button
                      onClick={() => setTargetMode('frequency')}
                      className={`p-4 rounded-xl border-2 transition-all ${
                        targetMode === 'frequency'
                          ? 'border-blue-500 bg-blue-50 dark:bg-blue-900/20'
                          : 'border-gray-200 dark:border-gray-700 hover:border-gray-300 dark:hover:border-gray-600'
                      }`}
                    >
                      <div className="text-2xl mb-1">📅</div>
                      <div className="text-sm font-medium text-gray-900 dark:text-white mb-1">
                        按频率
                      </div>
                      <div className="text-xs text-gray-500 dark:text-gray-400">
                        每天/周/月完成N次
                      </div>
                    </button>
                    
                    <button
                      onClick={() => setTargetMode('duration')}
                      className={`p-4 rounded-xl border-2 transition-all ${
                        targetMode === 'duration'
                          ? 'border-blue-500 bg-blue-50 dark:bg-blue-900/20'
                          : 'border-gray-200 dark:border-gray-700 hover:border-gray-300 dark:hover:border-gray-600'
                      }`}
                    >
                      <div className="text-2xl mb-1">⏱️</div>
                      <div className="text-sm font-medium text-gray-900 dark:text-white mb-1">
                        按时长
                      </div>
                      <div className="text-xs text-gray-500 dark:text-gray-400">
                        累计时长达到目标
                      </div>
                    </button>
                  </div>
                </div>
                
                {/* 频率选择 */}
                <div>
                  <label className="block text-sm font-medium mb-3" style={{ color: '#1D1D1F' }}>
                    频率
                  </label>
                  <div className="grid grid-cols-4 gap-3">
                    {[
                      { value: 'daily' as const, label: '每日', emoji: '☀️' },
                      { value: 'weekly' as const, label: '每周', emoji: '📅' },
                      { value: 'monthly' as const, label: '每月', emoji: '🗓️' },
                      { value: 'yearly' as const, label: '每年', emoji: '📆' },
                    ].map((f) => (
                      <button
                        key={f.value}
                        onClick={() => setFrequency(f.value)}
                        className="p-3 rounded-xl border-2 transition-all active:scale-95"
                        style={{
                          borderColor: frequency === f.value ? '#DD617C' : 'rgba(0, 0, 0, 0.06)',
                          backgroundColor: frequency === f.value ? 'rgba(221, 97, 124, 0.1)' : '#FFFFFF'
                        }}
                      >
                        <div className="text-xl mb-1">{f.emoji}</div>
                        <div className="text-xs font-medium" style={{ color: '#1D1D1F' }}>
                          {f.label}
                        </div>
                      </button>
                    ))}
                  </div>
                </div>
                
                {/* 目标值 */}
                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-3">
                    目标
                    {type === 'duration' && ' (分钟)'}
                    {type === 'count' && ' (次)'}
                  </label>
                  <div className="flex items-center gap-4">
                    <button
                      onClick={() => setTargetValue(Math.max(1, targetValue - 1))}
                      className="w-12 h-12 rounded-xl bg-gray-100 dark:bg-gray-800 hover:bg-gray-200 dark:hover:bg-gray-700 flex items-center justify-center transition-colors"
                    >
                      <Minus className="w-5 h-5 text-gray-600 dark:text-gray-400" />
                    </button>
                    
                    <input
                      type="number"
                      value={targetValue}
                      onChange={(e) => setTargetValue(Math.max(1, parseInt(e.target.value) || 1))}
                      className="flex-1 px-4 py-3 rounded-xl bg-gray-50 dark:bg-gray-800 border border-gray-200 dark:border-gray-700 text-center text-2xl font-bold text-gray-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-blue-500"
                    />
                    
                    <button
                      onClick={() => setTargetValue(targetValue + 1)}
                      className="w-12 h-12 rounded-xl bg-gray-100 dark:bg-gray-800 hover:bg-gray-200 dark:hover:bg-gray-700 flex items-center justify-center transition-colors"
                    >
                      <Plus className="w-5 h-5 text-gray-600 dark:text-gray-400" />
                    </button>
                  </div>
                </div>
                
                {/* AI 识别设置 */}
                <div>
                  <div className="flex items-center justify-between mb-3">
                    <label className="text-sm font-medium text-gray-700 dark:text-gray-300">
                      AI 自动识别
                    </label>
                    <button
                      onClick={() => setEnableRecognition(!enableRecognition)}
                      className={`relative w-12 h-6 rounded-full transition-colors ${
                        enableRecognition
                          ? 'bg-gradient-to-r from-blue-500 to-purple-500'
                          : 'bg-gray-300 dark:bg-gray-700'
                      }`}
                    >
                      <motion.div
                        animate={{ x: enableRecognition ? 24 : 0 }}
                        className="absolute top-0.5 left-0.5 w-5 h-5 bg-white rounded-full shadow-md"
                      />
                    </button>
                  </div>
                  
                  {enableRecognition && (
                    <motion.div
                      initial={{ opacity: 0, height: 0 }}
                      animate={{ opacity: 1, height: 'auto' }}
                      exit={{ opacity: 0, height: 0 }}
                      className="space-y-4"
                    >
                      {/* 正向关键词 */}
                      <div>
                        <p className="text-xs text-gray-500 dark:text-gray-400 mb-2">
                          设置关键词，当任务标题或标签包含这些关键词时，自动记录到此习惯
                        </p>
                        
                        <div className="flex gap-2">
                          <input
                            type="text"
                            value={keywordInput}
                            onChange={(e) => setKeywordInput(e.target.value)}
                            onKeyPress={(e) => e.key === 'Enter' && addKeyword()}
                            placeholder="输入关键词"
                            className="flex-1 px-4 py-2 rounded-xl bg-gray-50 dark:bg-gray-800 border border-gray-200 dark:border-gray-700 text-gray-900 dark:text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500"
                          />
                          <button
                            onClick={addKeyword}
                            className="px-4 py-2 rounded-xl bg-blue-500 text-white hover:bg-blue-600 transition-colors"
                          >
                            添加
                          </button>
                        </div>
                        
                        {keywords.length > 0 && (
                          <div className="flex flex-wrap gap-2 mt-2">
                            {keywords.map((keyword) => (
                              <div
                                key={keyword}
                                className="flex items-center gap-2 px-3 py-1.5 rounded-full bg-purple-100 dark:bg-purple-900/30 text-purple-600 dark:text-purple-400 text-sm"
                              >
                                <span>{keyword}</span>
                                <button
                                  onClick={() => removeKeyword(keyword)}
                                  className="hover:text-purple-800 dark:hover:text-purple-200"
                                >
                                  <X className="w-3 h-3" />
                                </button>
                              </div>
                            ))}
                          </div>
                        )}
                      </div>
                      
                      {/* 反向检测规则 */}
                      <div className="border-t border-gray-200 dark:border-gray-700 pt-4">
                        <div className="flex items-center justify-between mb-3">
                          <div>
                            <label className="text-sm font-medium text-gray-700 dark:text-gray-300">
                              反向检测规则
                            </label>
                            <p className="text-xs text-gray-500 dark:text-gray-400 mt-0.5">
                              在指定时间段内未找到关键词则算完成（如：不熬夜）
                            </p>
                          </div>
                          <button
                            onClick={() => setEnableReverseDetection(!enableReverseDetection)}
                            className={`relative w-12 h-6 rounded-full transition-colors ${
                              enableReverseDetection
                                ? 'bg-gradient-to-r from-orange-500 to-red-500'
                                : 'bg-gray-300 dark:bg-gray-700'
                            }`}
                          >
                            <motion.div
                              animate={{ x: enableReverseDetection ? 24 : 0 }}
                              className="absolute top-0.5 left-0.5 w-5 h-5 bg-white rounded-full shadow-md"
                            />
                          </button>
                        </div>
                        
                        {enableReverseDetection && (
                          <motion.div
                            initial={{ opacity: 0, height: 0 }}
                            animate={{ opacity: 1, height: 'auto' }}
                            className="space-y-3"
                          >
                            {/* 时间范围 */}
                            <div className="bg-orange-50 dark:bg-orange-900/20 rounded-xl p-3 space-y-3">
                              <div className="flex items-center gap-2 text-sm text-gray-700 dark:text-gray-300">
                                <Clock className="w-4 h-4" />
                                <span className="font-medium">检测时间段</span>
                              </div>
                              
                              <div className="grid grid-cols-2 gap-3">
                                <div>
                                  <label className="block text-xs text-gray-600 dark:text-gray-400 mb-1">
                                    开始时间
                                  </label>
                                  <input
                                    type="time"
                                    value={reverseStartTime}
                                    onChange={(e) => setReverseStartTime(e.target.value)}
                                    className="w-full px-3 py-2 rounded-lg bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 text-gray-900 dark:text-white text-sm focus:outline-none focus:ring-2 focus:ring-orange-500"
                                  />
                                </div>
                                
                                <div>
                                  <label className="block text-xs text-gray-600 dark:text-gray-400 mb-1">
                                    结束时间
                                  </label>
                                  <input
                                    type="time"
                                    value={reverseEndTime}
                                    onChange={(e) => setReverseEndTime(e.target.value)}
                                    className="w-full px-3 py-2 rounded-lg bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 text-gray-900 dark:text-white text-sm focus:outline-none focus:ring-2 focus:ring-orange-500"
                                  />
                                </div>
                              </div>
                              
                              <label className="flex items-center gap-2 text-sm">
                                <input
                                  type="checkbox"
                                  checked={reverseCrossDay}
                                  onChange={(e) => setReverseCrossDay(e.target.checked)}
                                  className="w-4 h-4 rounded border-gray-300 text-orange-500 focus:ring-orange-500"
                                />
                                <span className="text-gray-700 dark:text-gray-300">
                                  跨天（如：23:00 - 次日 05:00）
                                </span>
                              </label>
                            </div>
                            
                            {/* 反向关键词 */}
                            <div>
                              <label className="block text-xs text-gray-600 dark:text-gray-400 mb-2">
                                未找到以下关键词则算完成
                              </label>
                              
                              <div className="flex gap-2">
                                <input
                                  type="text"
                                  value={reverseKeywordInput}
                                  onChange={(e) => setReverseKeywordInput(e.target.value)}
                                  onKeyPress={(e) => e.key === 'Enter' && addReverseKeyword()}
                                  placeholder="如：工作、学习、熬夜"
                                  className="flex-1 px-4 py-2 rounded-xl bg-gray-50 dark:bg-gray-800 border border-gray-200 dark:border-gray-700 text-gray-900 dark:text-white placeholder-gray-400 text-sm focus:outline-none focus:ring-2 focus:ring-orange-500"
                                />
                                <button
                                  onClick={addReverseKeyword}
                                  className="px-4 py-2 rounded-xl bg-orange-500 text-white hover:bg-orange-600 transition-colors text-sm"
                                >
                                  添加
                                </button>
                              </div>
                              
                              {reverseKeywords.length > 0 && (
                                <div className="flex flex-wrap gap-2 mt-2">
                                  {reverseKeywords.map((keyword) => (
                                    <div
                                      key={keyword}
                                      className="flex items-center gap-2 px-3 py-1.5 rounded-full bg-orange-100 dark:bg-orange-900/30 text-orange-600 dark:text-orange-400 text-sm"
                                    >
                                      <span>{keyword}</span>
                                      <button
                                        onClick={() => removeReverseKeyword(keyword)}
                                        className="hover:text-orange-800 dark:hover:text-orange-200"
                                      >
                                        <X className="w-3 h-3" />
                                      </button>
                                    </div>
                                  ))}
                                </div>
                              )}
                              
                              <p className="text-xs text-gray-500 dark:text-gray-400 mt-2">
                                💡 示例：晚上11点到凌晨5点，未找到"工作"、"学习"等关键词，则算作"不熬夜"完成
                              </p>
                            </div>
                          </motion.div>
                        )}
                      </div>
                    </motion.div>
                  )}
                </div>
                
                {/* 描述 */}
                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    描述（可选）
                  </label>
                  <textarea
                    value={description}
                    onChange={(e) => setDescription(e.target.value)}
                    placeholder="添加一些备注..."
                    rows={3}
                    className="w-full px-4 py-3 rounded-xl bg-gray-50 dark:bg-gray-800 border border-gray-200 dark:border-gray-700 text-gray-900 dark:text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500 resize-none"
                  />
                </div>
              </div>
              
              {/* 底部按钮区域 - 固定在底部 */}
              <div className="border-t px-6 py-4 flex gap-3 flex-shrink-0" style={{
                backgroundColor: '#FFFFFF',
                borderColor: 'rgba(0, 0, 0, 0.06)'
              }}>
                <button
                  onClick={onClose}
                  className="flex-1 py-3 rounded-full font-semibold text-sm transition-all active:scale-95"
                  style={{
                    backgroundColor: '#F5F5F7',
                    color: '#1D1D1F'
                  }}
                >
                  取消
                </button>
                <button
                  onClick={handleSubmit}
                  disabled={!name.trim()}
                  className="flex-1 py-3 rounded-full font-semibold text-sm shadow-lg transition-all active:scale-95 disabled:opacity-50 disabled:cursor-not-allowed"
                  style={{
                    backgroundColor: '#6D9978',
                    color: '#FFFFFF'
                  }}
                >
                  保存
                </button>
              </div>
            </motion.div>
          </div>
        </>
      )}
    </AnimatePresence>
  );
}

