import { motion } from 'framer-motion';
import { useHabitStore } from '@/stores/habitStore';
import type { Habit } from '@/types/habit';
import { Check } from 'lucide-react';

interface HabitListProps {
  habits: Habit[];
  onHabitClick: (habitId: string) => void;
}

export default function HabitList({ habits, onHabitClick }: HabitListProps) {
  const logHabit = useHabitStore((state) => state.logHabit);
  const getLogsForDate = useHabitStore((state) => state.getLogsForDate);
  
  const today = new Date().toISOString().split('T')[0];
  const todayLogs = getLogsForDate(today);
  
  const handleQuickLog = (e: React.MouseEvent, habitId: string, targetValue: number) => {
    e.stopPropagation();
    logHabit(habitId, targetValue);
  };
  
  const isCompletedToday = (habitId: string, targetValue: number) => {
    const logs = todayLogs.filter((l) => l.habitId === habitId);
    const totalValue = logs.reduce((sum, l) => sum + l.value, 0);
    return totalValue >= targetValue;
  };
  
  const getTodayProgress = (habitId: string, targetValue: number) => {
    const logs = todayLogs.filter((l) => l.habitId === habitId);
    const totalValue = logs.reduce((sum, l) => sum + l.value, 0);
    return Math.min((totalValue / targetValue) * 100, 100);
  };
  
  return (
    <div className="space-y-3">
      {habits.map((habit, index) => {
        const completed = isCompletedToday(habit.id, habit.targetValue);
        const progress = getTodayProgress(habit.id, habit.targetValue);
        
        return (
          <motion.div
            key={habit.id}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: index * 0.05 }}
            onClick={() => onHabitClick(habit.id)}
            className="bg-white dark:bg-gray-800 rounded-2xl p-4 shadow-sm hover:shadow-md transition-all cursor-pointer border border-gray-100 dark:border-gray-700"
          >
            <div className="flex items-center gap-4">
              {/* Emoji 图标 */}
              <div className="relative">
                <div className="w-14 h-14 rounded-2xl bg-gradient-to-br from-blue-100 to-purple-100 dark:from-blue-900/30 dark:to-purple-900/30 flex items-center justify-center text-2xl">
                  {habit.emoji}
                </div>
                {completed && (
                  <motion.div
                    initial={{ scale: 0 }}
                    animate={{ scale: 1 }}
                    className="absolute -top-1 -right-1 w-6 h-6 rounded-full bg-green-500 flex items-center justify-center"
                  >
                    <Check className="w-4 h-4 text-white" />
                  </motion.div>
                )}
              </div>
              
              {/* 习惯信息 */}
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2 mb-1">
                  <h3 className="font-semibold text-gray-900 dark:text-white truncate">
                    {habit.name}
                  </h3>
                  {habit.autoGenerated && (
                    <span className="px-2 py-0.5 rounded-full bg-purple-100 dark:bg-purple-900/30 text-purple-600 dark:text-purple-400 text-xs font-medium">
                      AI
                    </span>
                  )}
                </div>
                
                <div className="flex items-center gap-3 text-sm text-gray-500 dark:text-gray-400">
                  <span>
                    {habit.frequency === 'daily' && '每日'}
                    {habit.frequency === 'weekly' && '每周'}
                    {habit.frequency === 'monthly' && '每月'}
                    {habit.frequency === 'yearly' && '每年'}
                  </span>
                  <span>•</span>
                  <span>
                    目标 {habit.targetValue}
                    {habit.type === 'duration' && ' 分钟'}
                    {habit.type === 'count' && ' 次'}
                  </span>
                  {habit.currentStreak > 0 && (
                    <>
                      <span>•</span>
                      <span className="text-orange-500 dark:text-orange-400 font-medium">
                        🔥 {habit.currentStreak} 天
                      </span>
                    </>
                  )}
                </div>
                
                {/* 进度条 */}
                <div className="mt-2 h-2 bg-gray-100 dark:bg-gray-700 rounded-full overflow-hidden">
                  <motion.div
                    initial={{ width: 0 }}
                    animate={{ width: `${progress}%` }}
                    transition={{ duration: 0.5, ease: 'easeOut' }}
                    className={`h-full rounded-full ${
                      completed
                        ? 'bg-gradient-to-r from-green-400 to-green-500'
                        : 'bg-gradient-to-r from-blue-400 to-purple-500'
                    }`}
                  />
                </div>
              </div>
              
              {/* 快速打卡按钮 */}
              {!completed && (
                <button
                  onClick={(e) => handleQuickLog(e, habit.id, habit.targetValue)}
                  className="w-12 h-12 rounded-xl bg-gradient-to-r from-blue-500 to-purple-500 text-white flex items-center justify-center hover:shadow-lg transition-all active:scale-95"
                >
                  <Plus className="w-6 h-6" />
                </button>
              )}
            </div>
          </motion.div>
        );
      })}
    </div>
  );
}

function Plus({ className }: { className?: string }) {
  return (
    <svg
      className={className}
      fill="none"
      stroke="currentColor"
      viewBox="0 0 24 24"
    >
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={2}
        d="M12 4v16m8-8H4"
      />
    </svg>
  );
}


