// ============================================
// 习惯追踪系统类型定义
// ============================================

export type HabitFrequency = 'daily' | 'weekly' | 'monthly' | 'yearly';
export type HabitType = 'count' | 'duration' | 'boolean';

// 习惯记录
export interface HabitLog {
  id: string;
  habitId: string;
  date: string; // YYYY-MM-DD
  value: number; // 次数/时长/0或1
  timestamp: Date;
  note?: string;
  relatedTaskIds?: string[]; // 关联的任务ID
}

// 习惯识别规则
export interface HabitRecognitionRule {
  keywords: string[]; // 关键词列表
  matchTitle: boolean; // 是否匹配标题
  matchTags: boolean; // 是否匹配标签
  minDuration?: number; // 最小时长（分钟）
  taskTypes?: string[]; // 任务类型限制
  
  // 反向检测规则（用于熬夜等场景）
  reverseDetection?: {
    enabled: boolean; // 是否启用反向检测
    timeRange: {
      startTime: string; // 开始时间 HH:mm
      endTime: string; // 结束时间 HH:mm
      crossDay: boolean; // 是否跨天（如23:00-05:00）
    };
    notFoundKeywords: string[]; // 未找到这些关键词时算完成
  };
}

// 自动生成规则配置
export interface AutoGenerationRule {
  enabled: boolean;
  dailyThreshold: number; // 连续N天每天做，生成日习惯
  weeklyThreshold: number; // 连续N周每周做M次，生成周习惯
  weeklyMinCount: number; // 每周最少次数
  monthlyThreshold: number; // 连续N月每月做M次，生成月习惯
  monthlyMinCount: number; // 每月最少次数
}

// 习惯定义
export interface Habit {
  id: string;
  userId: string;
  name: string;
  emoji: string;
  description?: string;
  
  // 习惯类型
  type: HabitType; // 计数型/时长型/布尔型
  frequency: HabitFrequency; // 日/周/月/年
  
  // 目标设置模式
  targetMode: 'frequency' | 'duration'; // 频率模式 or 持续时间模式
  targetValue: number; // 目标值（次数/分钟/1）
  targetPeriod: number; // 目标周期（1=每天/每周/每月，7=每7天）
  
  // 识别规则
  recognitionRule?: HabitRecognitionRule;
  autoGenerated: boolean; // 是否AI自动生成
  
  // 统计数据
  currentStreak: number; // 当前连续天数
  longestStreak: number; // 最长连续天数
  totalCount: number; // 总完成次数
  totalDuration: number; // 总时长（分钟）
  
  // 完成率统计
  completionRate: {
    daily?: number; // 日完成率
    weekly?: number; // 周完成率
    monthly?: number; // 月完成率
  };
  
  // 时间信息
  createdAt: Date;
  updatedAt: Date;
  archivedAt?: Date; // 归档时间
  
  // 提醒设置
  reminderEnabled: boolean;
  reminderTime?: string; // HH:mm
  
  // 颜色标识
  color?: string;
  
  // 排序
  sortOrder: number;
}

// 习惯统计数据
export interface HabitStats {
  habitId: string;
  period: 'week' | 'month' | 'year';
  startDate: string;
  endDate: string;
  
  // 完成情况
  completedDays: number;
  totalDays: number;
  completionRate: number;
  
  // 连续性
  currentStreak: number;
  longestStreak: number;
  
  // 趋势
  trend: 'up' | 'down' | 'stable';
  trendPercentage: number;
  
  // 每日数据
  dailyData: {
    date: string;
    value: number;
    completed: boolean;
  }[];
}

// 习惯候选（AI识别出的潜在习惯）
export interface HabitCandidate {
  id: string;
  name: string;
  emoji: string;
  frequency: HabitFrequency;
  type: HabitType;
  
  // 识别数据
  detectedKeywords: string[];
  occurrences: {
    date: string;
    taskId: string;
    taskTitle: string;
    value: number;
  }[];
  
  // 统计
  totalOccurrences: number;
  consecutiveDays: number;
  consecutiveWeeks: number;
  consecutiveMonths: number;
  
  // 建议
  suggestedTarget: number;
  confidence: number; // 0-1，识别置信度
  
  // 状态
  status: 'pending' | 'accepted' | 'rejected';
  createdAt: Date;
}

// 习惯分组
export interface HabitGroup {
  id: string;
  name: string;
  emoji: string;
  color: string;
  habitIds: string[];
  sortOrder: number;
}

